"""Generate the 15 verification CSVs for Simo-Ju + Weibull (Phase 5).

For each of the 15 published Brandyberry (2022) curves across Fig 1(c),
Fig 11(a), and Fig 11(b), compute the reference stress-strain trace via
the pure-numpy Simo-Ju Phase 1 reference (tutorial/simo_ju/phase1_reference.py)
and write one v3-format verification CSV per curve.

Because the Brandyberry plots are synthetic (generated by the same equations
we implemented), the reference and the model agree to machine precision.
The NEML2 Verification driver will read each CSV and confirm bit-equivalence.

CSV format (v3 verification convention; 13 columns):
    time, strain_xx, strain_yy, strain_zz, strain_yz, strain_xz, strain_xy,
          stress_xx, stress_yy, stress_zz, stress_yz, stress_xz, stress_xy

Under uniaxial stress: lateral strains = -nu * eps_xx (ties into
LinearIsotropicElasticity's Poisson ratio, so off-axis effective stresses
are exactly zero). Only sigma_xx is nonzero.

Re-run this script if the reference formulas ever change:
    python make_verification_csvs.py
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

import numpy as np

# Import from the tutorial directory
_HERE = Path(__file__).parent
_TUTORIAL = _HERE.parents[3] / "tutorial" / "simo_ju"
sys.path.insert(0, str(_TUTORIAL))
from phase1_reference import simulate_uniaxial  # noqa: E402

# ---------------------------------------------------------------------------
# Common material + loading configuration
# ---------------------------------------------------------------------------

E = 2.5e9  # Pa
NU = 0.3
STRAIN_MAX = 1.0e-3  # 1 permille — matches Brandyberry's x-axis in Fig 1(c) + 11
N_STEPS = 200  # per-CSV; keeps files small while resolving cliff shapes


def _write_csv(out_path: Path, strain_xx: np.ndarray, stress_xx: np.ndarray) -> None:
    """Write one v3-format verification CSV.

    Prepends a virgin t=0 row (all zeros); subsequent rows carry the
    prescribed strain state and expected stress. Lateral strains follow
    the isotropic Poisson relation so off-axis effective-stress components
    are exactly zero and the composed NEML2 model traces sigma_xx only.
    """
    header = [
        "time",
        "strain_xx", "strain_yy", "strain_zz",
        "strain_yz", "strain_xz", "strain_xy",
        "stress_xx", "stress_yy", "stress_zz",
        "stress_yz", "stress_xz", "stress_xy",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        # Include the t=0 virgin state
        w.writerow(["0"] + ["0"] * 12)
        for k, (eps, sig) in enumerate(zip(strain_xx, stress_xx, strict=True), start=1):
            lat = -NU * eps
            row = [
                float(k),
                eps, lat, lat, 0.0, 0.0, 0.0,
                sig, 0.0, 0.0, 0.0, 0.0, 0.0,
            ]
            w.writerow([f"{x:.18e}" for x in row])


def _param_slug(value: float) -> str:
    """Formatting helper: 0.01 -> '0p01', 100 -> '100'."""
    if value == int(value):
        return str(int(value))
    return str(value).replace(".", "p")


def gen_fig1c_curves() -> list[tuple[str, dict]]:
    """Brandyberry Fig 1(c) — p1 sweep at fixed (E, Y_in, p2=1)."""
    p1_values = [0.01, 0.1, 1.0, 10.0, 100.0]
    Y_in = 300.0
    p2 = 1.0
    curves = []
    for p1 in p1_values:
        name = f"fig1c_p1_{_param_slug(p1)}"
        curves.append((name, {"Y_in": Y_in, "p1": p1, "p2": p2}))
    return curves


def gen_fig11a_curves() -> list[tuple[str, dict]]:
    """Brandyberry Fig 11(a) — Y_in sweep at fixed (E, p1=1, p2=1)."""
    Y_in_values = [100.0, 200.0, 300.0, 400.0, 500.0]
    p1 = 1.0
    p2 = 1.0
    curves = []
    for Y_in in Y_in_values:
        name = f"fig11a_Yin_{_param_slug(Y_in)}"
        curves.append((name, {"Y_in": Y_in, "p1": p1, "p2": p2}))
    return curves


def gen_fig11b_curves() -> list[tuple[str, dict]]:
    """Brandyberry Fig 11(b) — p2 sweep at fixed (E, Y_in=300, p1=1)."""
    p2_values = [0.01, 0.1, 1.0, 10.0, 100.0]
    Y_in = 300.0
    p1 = 1.0
    curves = []
    for p2 in p2_values:
        name = f"fig11b_p2_{_param_slug(p2)}"
        curves.append((name, {"Y_in": Y_in, "p1": p1, "p2": p2}))
    return curves


def main() -> None:
    strain_xx = np.linspace(STRAIN_MAX / N_STEPS, STRAIN_MAX, N_STEPS)
    print(f"Simo-Ju verification CSV generator (E={E:.2e} Pa, strain 0 to {STRAIN_MAX} in {N_STEPS} steps)")
    all_curves = gen_fig1c_curves() + gen_fig11a_curves() + gen_fig11b_curves()
    for name, params in all_curves:
        result = simulate_uniaxial(strain_xx, E=E, **params)
        out_path = _HERE / name / f"{name}.csv"
        _write_csv(out_path, strain_xx, result["stress"])
        print(f"  wrote {out_path.relative_to(_HERE.parents[3])}  "
              f"(Y_in={params['Y_in']:g}, p1={params['p1']:g}, p2={params['p2']:g}, "
              f"peak_sigma={result['stress'].max() * 1e-6:.3f} MPa)")

    print(f"\nGenerated {len(all_curves)} verification CSVs under {_HERE}")


if __name__ == "__main__":
    main()
