"""Generate the 15 verification .i files for the Simo-Ju CSVs.

Reads the CSV metadata written by make_verification_csvs.py and emits one
`<name>.i` per curve. Each .i has the identical composed-model block; only
the WeibullDamage parameters (Y_in, p1, p2) differ.

Tolerances: rtol=1e-6, atol=1e-3 Pa. The CSVs come from our own Python
reference, which uses identical formulas to the NEML2 composed model, so
we expect machine-precision agreement. Wider than machine precision to
absorb pytest float roundoff.
"""

from __future__ import annotations

import sys
from pathlib import Path

_HERE = Path(__file__).parent
sys.path.insert(0, str(_HERE))
from make_verification_csvs import (  # noqa: E402
    gen_fig11a_curves,
    gen_fig11b_curves,
    gen_fig1c_curves,
)

_TEMPLATE = """# Verification scenario: Simo-Ju + Weibull vs pure-Python reference.
# Curve: {curve_name}
# Parameters: Y_in = {Y_in:g},  p1 = {p1:g},  p2 = {p2:g}
#
# The reference CSV was generated by make_verification_csvs.py, which uses
# tutorial/simo_ju/phase1_reference.py under identical formulas. The NEML2
# composed model must reproduce it to machine precision at each strain
# point.

[Tensors]
  [times]
    type = CSVScalar
    csv_file = '{csv_name}'
    variable = 'time'
  []
  [strains]
    type = CSVSR2
    csv_file = '{csv_name}'
    variable = 'strain'
  []
  [stresses]
    type = CSVSR2
    csv_file = '{csv_name}'
    variable = 'stress'
  []
[]

[Drivers]
  [driver]
    type = TransientDriver
    model = 'model'
    prescribed_time = 'times'
    prescribed_SR2_names = 'E'
    prescribed_SR2_values = 'strains'
    save_as = 'result.pt'
  []
  [verification]
    type = Verification
    driver = 'driver'
    SR2_names = 'output.sigma'
    SR2_values = 'stresses'
    rtol = 1e-6
    atol = 1e-3
  []
[]

[Models]
  [effective_stress]
    type              = LinearIsotropicElasticity
    coefficients      = '2.5e9 0.3'
    coefficient_types = 'YOUNGS_MODULUS POISSONS_RATIO'
    strain            = 'E'
    stress            = 'sigma_tilde'
  []
  [strain_energy]
    type              = LinearIsotropicStrainEnergyDensity
    coefficients      = '2.5e9 0.3'
    coefficient_types = 'YOUNGS_MODULUS POISSONS_RATIO'
    decomposition     = 'NONE'
    strain            = 'E'
    active_strain_energy_density   = 'psi0'
    inactive_strain_energy_density = 'psi0_unused'
  []
  [damage_history]
    type = IrreversibleScalar
    from = 'psi0'
    to   = 'r'
  []
  [weibull]
    type = WeibullDamage
    r    = 'r'
    D    = 'D_step'
    Y_in = {Y_in:g}
    p1   = {p1:g}
    p2   = {p2:g}
  []
  [damage_monotone]
    type = IrreversibleScalar
    from = 'D_step'
    to   = 'D'
  []
  [damaged_stress]
    type             = DamagedStress
    damage           = 'D'
    effective_stress = 'sigma_tilde'
    stress           = 'sigma'
  []
  [model]
    type               = ComposedModel
    models             = 'effective_stress strain_energy damage_history weibull damage_monotone damaged_stress'
    additional_outputs = 'D r psi0 sigma_tilde'
  []
[]
"""


def main() -> None:
    all_curves = gen_fig1c_curves() + gen_fig11a_curves() + gen_fig11b_curves()
    for name, params in all_curves:
        out_dir = _HERE / name
        out_dir.mkdir(parents=True, exist_ok=True)
        i_path = out_dir / f"{name}.i"
        i_path.write_text(_TEMPLATE.format(curve_name=name, csv_name=f"{name}.csv", **params))
        print(f"  wrote {i_path.relative_to(_HERE.parents[3])}")


if __name__ == "__main__":
    main()
